name: Build and Deploy Project

on:
  push:
    branches: [master]
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Angular App
        run: npm run build:prod
        
      - name: Deploy to gh pages
        run: |
          npx ng deploy --repo=https://github.com/cainaican/ruki.git --name="cainaican" --email=musindinislam1@yandex.ru
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
